version: '3.1'

services:
  db:
    image: mariadb:latest
    ports:
      - "14401:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=pass"
      - "MYSQL_DATABASE=mariadb"
    volumes:
      - db-data-volume:/var/lib/mariadb
volumes:
  db-data-volume: